name: multi event pipeline / workflow
on:
  push:
    branches:
      - master
      - main
      
jobs:
    on push
        runs-on: ubuntu-latest
        steps:
            - name: "running on main push"
              run: echo "Running on master push"



