name: multi event pipeline / workflow
on:
  push:
    branches:
      - main
  pull_request: 
       branches:
           - main
      
jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "running on main push"
              run: echo "Running on master push"
    on-pull-request:
        runs-on: ubuntu-latest
        steps:
            - name: "running on pull request"
              run: echo "running on pull request"
        

     


